### ISSUE TITLE
Threading for stm32f103?

### ISSUE THREAD

**Issue by mwshakoor154** [terjeio/grblHAL#215]
Is there any plugin for threading on stm32f103 boards?

**Comment by terjeio** [comment]
I am sorry no, and I will not add threading for this processor due to lack of a FPU and limited RAM/flash. There are also many cloned and fake processors on the market for the red & bluepill boards so better avoid them for new projects.

MSP432, STMF4xx and iMRX1062 (Teensy 4.1) are the processors I currently want to support threading for. When these have implementations that are considered stable then I _may_ consider adding support for more.

Note that the STM32F411 Blackpill does not have the neccesary pins brought out for the current spindle encoder input configuration. A Nucleo-64 devboard for F411 or F446 is required.

Of course if anybody want to implement driver support for threading for other processors then by all means do that but IMO it would be better if we could join forces to get one or more of the three processor implementations mentioned above validated first.
